### ISSUE TITLE
TypeError: private_value must be an integer type.

### ISSUE THREAD

**Issue by eychei** [bitlogik/lattice-attack#1]
Hello,

I just tried your code and it does not work for me. Hope you can help out.

Getting the following error:

 ----- Lattice ECDSA Attack -----
Loading data from file test
Running with 8 bits of k (LSB)
Starting recovery attack (curve SECP256K1)
Constructing matrix
Solving matrix ...
LLL reduction
Traceback (most recent call last):
  File "lattice_attack.py", line 259, in <module>
    lattice_attack_cli(arg.f, arg.l)
  File "lattice_attack.py", line 240, in lattice_attack_cli
    signatures, hash_int, q_target, curve_string, data_type, known_bits, loop
  File "lattice_attack.py", line 195, in recover_private_key
    res = test_result(lattice, pub_key, curve)
  File "lattice_attack.py", line 93, in test_result
    if target_pubkey == ecdsa_lib.privkey_to_pubkey(cand1, curve):
  File "/mnt/c/users/think/downloads/lattice-attack-master/ecdsa_lib.py", line 129, in privkey_to_pubkey
    ec.derive_private_key(pv_key_int, ec_backend, backends.default_backend())
  File "/home/breaker/miniconda3/envs/bddp/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 347, in derive_private_key
    raise TypeError("private_value must be an integer type.")
TypeError: private_value must be an integer type.

Thank you.

-e

**Comment by bitlogik** [comment]
Maybe this LatticeAttack software doesn't run properly on Python Anaconda flavor, or with some versions of fpylll. Can you detail the Python version, your OS, and the fpylll version ? At this stage I don't exclude a bug where on specific installation, the fpylll doesn't handle back integers type to the Python code.

Try the given demos, to see if the same issue appears :
`python3 gen_data.py && python3 lattice_attack.py`  
and also  
```
cd Data/ECDummyRPA/
python3 gen_input.py && python3 ../../lattice_attack.py
```

Try with the following change in line 89 in lattice_attack.py : 
`candidate = int(row[-2]) % mod_n`
To help in the investigation, you can also add the line just before :
`print(type(row[-2]))`

Finally, check that you put integers everywhere : message bytes list (in case same message for all signatures), r, s, public key (x, y), kp, signatures (r, s), hash, and known_bits.

**Comment by eychei** [comment]
Hi,

Thanks for the fast response.
I will provide os and software version tomorrow.
I did use the gen_data.py to generate data and also used the ECDummy data. Both give the same error. I also tried installing the package on a VM but got the same error. Which Linux distro are you using? I will setup the same and try again with all your suggestions.

-e

**Comment by eychei** [comment]
Here is my OS and package info:
Ubuntu 21.04
Python 3.9.5
python3-fpylll  0.5.2+ds1-3

-e

**Comment by bitlogik** [comment]
We tested with the following machine :
VM, AMD64
US English
Ubuntu 21.04
CPython 3.9.5
python3-fpylll 0.5.2+ds1-3

And everything worked fine, the 2 examples (_gen_data_ and _Data/ECDummyRPA/gen_input_) ran flawlessly.

We think about a couple of causes that lead to this error :

You may have installed fpylll for an other software using other installation method from apt, eventually install from source, and it uses that library version instead which can be not compatible for the binding. Best option is to remove the python3-fpylll package and see if the LatticeAttack scripts complain about it missing.

Your data input file format was not full of integers as it should.

It may be also that you reported a wrong OS and Python version. We can read `miniconda3/envs/bddp/lib/python3.7` in the initial log you provided, which doesn't match the info you provided later.

Let us know more details, and clarify some point from your side, and we'll look at this again. Would be worthwhile to have the detailed reproducible steps which lead to this issue.

**Comment by eychei** [comment]
Hi,

thanks for the follow up. I did try on different OSes and installations. But you may be right that I had fpylll installed from another package. I was testing other sources and installed the packages accordingly. Was to lazy to do a fresh install of ubuntu on my vm.
I will start with a fresh image and try again. Will post an update.

Thanks.

-e

**Comment by bitlogik** [comment]
A fast and easy method to get a working Ubuntu 21.04 VM in seconds, is to run the Lubuntu 21.04 ISO. That doesn't even require any disk drive, no installation, you get a full working system in seconds.

**Comment by mikejnpc** [comment]
Hello .... i have the same issue and ran the standard tests which failed.  (see below)
however i will go ahead and make the adjustments as suggested unless if there is something else required? ... 

-- i read the other mention and do have sage installed, i do not want to uninstall it if possible. 
is it calling on sage to run the function? 

python3 gen_data.py && python3 lattice_attack.py
Preparing Data
Private key to be found (as demo) :
0xcec2aae13662edec1d64641daeba0c95c916e7245a68e8c7eb2828cbdb9142c1
Generating 1000 signatures with curve SECP256K1
 leaking 6 bits for k (LSB)  ...
File data.json written with all data.

 ----- Lattice ECDSA Attack -----
Loading data from file data.json
Running with 6 bits of k (LSB)
Starting recovery attack (curve SECP256K1)
Constructing matrix
Solving matrix ...
LLL reduction
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "lattice_attack.py", line 259, in <module>
    lattice_attack_cli(arg.f, arg.l)
  File "lattice_attack.py", line 239, in lattice_attack_cli
    result = recover_private_key(
  File "lattice_attack.py", line 195, in recover_private_key
    res = test_result(lattice, pub_key, curve)
  File "lattice_attack.py", line 93, in test_result
    if target_pubkey == ecdsa_lib.privkey_to_pubkey(cand1, curve):
  File "/mnt/c/Users/Michael/Documents/Desktop/lattice-attack-master/ecdsa_lib.py", line 129, in privkey_to_pubkey
    ec.derive_private_key(pv_key_int, ec_backend, backends.default_backend())
  File "/home/mjo/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 332, in derive_private_key
    raise TypeError("private_value must be an integer type.")
TypeError: private_value must be an integer type.

**Comment by bitlogik** [comment]
Our understanding so far is the following :
If the machine has Sage installed, fpylll installation uses Sage instead of GMP. Or similarly, big integers are automatically converted to sage elements. So elements in the matrix are sage.rings.integer.Integer and can't be automatically converted to Python integer. So when Sage is installed this fails. Also when Sage is present, using Sage class elements, we have reports that the processing is 5 times slower. You can find more details about remediation here : https://github.com/bitlogik/lattice-attack/issues/8#issuecomment-1143539363.

We'll investigate to see what is the difference exactly, how and when it is changed, and if we can force to avoid using Sage when it is installed.

**Comment by bitlogik** [comment]
The conversion is done by fpylll if Sage is installed. Integers are converted to sage.rings.integer.Integer during matrix writing (set elements), and/or just when read back from the matrix.
As [fpylll is fully automatic regarding this point](https://github.com/fplll/fpylll/blob/master/src/fpylll/io.pyx#L19). So there's no option to tell it to use or not.
Still, one way can be to use virtual env, so it won't detect Sage installed.

`python3 -m venv laenv`

Windows venv activation
```
# In cmd.exe
laenv\Scripts\activate.bat
```
```
# In PowerShell
laenv\Scripts\Activate.ps1
```
Linux and MacOS venv activation
```
$ source laenv/bin/activate
```

In this isolated environment, fpylll should not detect Sage.

Then at the end `deactivate`.

**Comment by smartunia** [comment]
Can u give a hint where to find jaon file? Because what i found is really different from yours i tried fetch json from blockchain my address transaction
