### ISSUE TITLE
ecdummyrpa ram

### ISSUE THREAD

**Issue by cloudkeychain** [bitlogik/lattice-attack#13]
How much ram is needed to build the ecdummyrpa data file?

**Comment by bitlogik** [comment]
You mean to run gen_input in the /Data/ECDummyRPA/sample directory ?
I don't know exactly, I tested, it is around 100 MB.
The files extracted is made by 6000 traces of 1450 bytes each.

Honestly, I don't think it's a concern. Except if you work on a small system with <1 GB RAM. But then you'll be limited for the LatticeAttack (matrix recovery).
I have never ever faced issue with RAM using this software. Still, I never used a computed with very low amount of RAM to use this. And I wouldn't recommend to use any small system with low RAM (<2GB total) to run LatticeAttack.

**Comment by cloudkeychain** [comment]
> You mean to run gen_input in the /Data/ECDummyRPA/sample directory ? I don't know exactly, I tested, it is around 100 MB. The files extracted is made by 6000 traces of 1450 bytes each.
> 
> Honestly, I don't think it's a concern. Except if you work on a small system with <1 GB RAM. But then you'll be limited for the LatticeAttack (matrix recovery). I have never ever faced issue with RAM using this software. Still, I never used a computed with very low amount of RAM to use this. And I wouldn't recommend to use any small system with low RAM (<2GB total) to run LatticeAttack.

thanks for reply. I attempted to try the ecdummyrpa using their docker and since the "bounds" was optional argument the container kept being killed without that argument when running the analysis.py due to not enough ram i believe. I then cloned this repo inside that container just to see if 6000 traces would work without "killed" error and ecdummyrpa container disconnected also after exceeding ram inside container. i'll try on a VM without using docker.

**Comment by bitlogik** [comment]
We can't help to build the data file, nor any input raw files, like generating the data from the traces. This ecdummyrpa software is not provided by us. We can only help you to use LatticeAttack, eventually converting the data to be used as input by LatticeAttack.
