### ISSUE TITLE
public key integer

### ISSUE THREAD

**Issue by cloudkeychain** [bitlogik/lattice-attack#14]
Having trouble trying to figure out how to convert uncompressed public key to integer. Is there a recommended way of doing this converting from pem or der format to integer?

**Comment by bitlogik** [comment]
An uncompressed public key is already a pair of integer (plane coordinates). But sometimes this is encoded in PEM or DER format.
You just need to decode the input format such as PEM or DER and extract the X,Y integers values.

In Python, you can use or be inspired by the helpers here in the ECDummyRPA demo :
https://github.com/bitlogik/lattice-attack/blob/master/Data/ECDummyRPA/gen_input.py#L58
 _pubkeyPEM_to_xy_ : convert a public key in PEM format to (x,y)
 _sigDER_to_ints_ : convert a signature DER format to (r,s)
 
 An other approach would be to use a cryptographic library, such as cryptography, and load the public key with a PEM format (with class method like ._fromPEM_), and then read the internal integers of the public key object ("public_numbers").
