### ISSUE TITLE
abdul

### ISSUE THREAD

**Issue by abduljhf** [bitlogik/lattice-attack#26]
This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fpylll                                                                                                                                                                              What do I care

**Comment by bitlogik** [comment]
I don't recommend compiling the fpyLLL library, as it is a complex task. Hence, we recommend that you install fpylll with the distribution package manager of your Linux. The package managers, such as apt or dnf, are providing all these, with pre-compiled binaries. Most of the Linux distributions are providing this package already compiled. On Ubuntu/debian for example, its name is _python3-fpylll_.

For some reasons, we don't recommend using LatticeAttack in combination with Sage. If Sage is needed for others software, an alternative is to run LatticeAttack in a virtual env (venv), so fpylll shoudn't detect Sage at runtime and should run right.

Can you share the operating system you are using? We could help further.

**Comment by Abdul35522** [comment]
I opened via pycharm and tried to install the fpyll library there, it gives the same error ERROR: Failed building wheel for fpylll What do I care

**Comment by Abdul35522** [comment]
is there a video of the launch?

**Comment by bitlogik** [comment]
Our recommendation is to install fpylll with the distribution package manager of your Linux. The package managers, such as _apt_ or _dnf_, provide all the pre-compiled binaries. On Ubuntu/Debian for example, its name is _python3-fpylll_. Otherwise, the compilation process is very complex, mostly because of the dependency library tree, and need the compilation tools.

Example to install fpylll in Ubuntu (>= 20.04) :
```
sudo add-apt-repository universe
sudo apt install python3-fpylll
```

**Comment by Abdul35522** [comment]
How can I contact you?

**Comment by Abdul35522** [comment]
How can I contact you? 
I have a lot of questions for you

**Comment by bitlogik** [comment]
Please send an email to contact@bitlogik.fr.

**Comment by Abdul35522** [comment]
I wrote to you

**Comment by Abdul35522** [comment]
i had a problem i renamed the data1.json file to data1.txt but when i renamed it back to .json the file remained in txt format how do i fix it?

**Comment by Abdul35522** [comment]
i fixed this problem.    I have questions, I don’t quite understand what is needed, where to insert it to find out the private key

**Comment by bitlogik** [comment]
What you can do to understand better what is needed and how to build the data :

- Read carefully the Readme file.
- Generate an example of input data with gen_data https://github.com/bitlogik/lattice-attack/blob/master/gen_data.py.
- Inspect [the code of LatticeAttack, some comments](https://github.com/bitlogik/lattice-attack/blob/master/lattice_attack.py) are helpful
- Read our long prose in this issue thread : https://github.com/bitlogik/lattice-attack/issues/21
- Read the bibliography provided in the Readme, to have a better understanding of the underlying principles.
