### ISSUE TITLE
Cant install fplll?

### ISSUE THREAD

**Issue by bane77111** [bitlogik/lattice-attack#27]
Any suggestion? Running on Mac OS.

```
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fpylll
  Running setup.py clean for fpylll
Failed to build fpylll
ERROR: Could not build wheels for fpylll, which is required to install pyproject.toml-based projects
```

**Comment by antonio-fr** [comment]
fpylll is recommended to be installed from pre-compiled binaries. Else it's very painful to compile it. I'm not aware of binary on Mac, means you need to compile it (how hard). Look at https://github.com/fplll/fpylll#getting-started, and particularly the note about MacOS (default GCC in MacOS is not very good for C++11, so requires clang and to specify export= to provide the options).
