### ISSUE TITLE
Video example

### ISSUE THREAD

**Issue by smartunia** [bitlogik/lattice-attack#28]
Can You make a video example for lattice attack without generating json file with random 

I wanna to say if is possible to make a real video

Because my English isn't so good to understand everything what is written. And i think most of viewers are in same situation 

We would be pleased if u do that for us

**Comment by bitlogik** [comment]
This post issue is very close from your question : https://github.com/bitlogik/lattice-attack/issues/24. Please read it carefully. We're sorry but the free support language is English here.

**Comment by bitlogik** [comment]
As for your use case, if you think that the nonce data comes from the blockchain, you're misleading. In the blockchain you have only data, signatures, public keys (only "public data"). This software requires addition "hidden" data. In our case partial information about the ECDSA internal nonce. Specifically the end or start value for each signature. Most of the time, this is for example knowing that the first 6 bits of the non are 0 (for all provided signatures). In the case you know a single secret nonce, or a linear relation between 2 (or more) nonces, the computation is different, and not covered by this software (computation in this case is more straightforward).
