### ISSUE TITLE
To json data converter request. Please.

### ISSUE THREAD

**Issue by Hurd8x** [bitlogik/lattice-attack#5]
Pleas, can you automate parse data from url and making .json output file ?

This is a secp256k1 hash contained r,s and posible calculate r,s,z of sighnature.

https://blockchain.info/rawtx/a4ad67ea73c88b635e003700290239e6beab7dc5c9b31f58cd34084418b7316d?format=hex

This scrupt help get all transaction hashes

https://github.com/CryptoXploit/bitcoin-key-compression/blob/main/R-Scaner.py

This for exact from transaction hash r,s,z
https://github.com/CryptoXploit/bitcoin-key-compression/blob/main/RawTX_RSZ.py

Regards.

**Comment by bitlogik** [comment]
Yes, we can. Please contact our team at : contact@bitlogik.fr and we'll provide a quote for such data parsing script. You can even chose if the code designed is public or private for you.

**Comment by Hurd8x** [comment]
> Yes, we can. Please contact our team at : [contact@bitlogik.fr](mailto:contact@bitlogik.fr) and we'll provide a quote for such data parsing script. You can even chose if the code designed is public or private for you.

Thank you very mach for your answer.

I was send you a email message.

Please check you email ASAP.

I waiting your answer to me.

Regards !!!
